[package]
name = "learn-RustLang"
version = "0.1.0"
authors = ["abdulsalam00 <aboubakar123678@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
